config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root to: "categories#index"
  resources :recipes, only: [ :index, :show ]
  resources :categories do
    resources :bookmarks, only: [ :new, :create, :destroy ]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe, uniqueness: { scope: :category }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories

  validates :name, presence: true
  validates :description, presence: true, uniqueness: true
  validates :rating, inclusion: { in: 0..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    # raise
    @bookmark = @category.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @category
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.find(params[:id])
    if @bookmark.destroy
      redirect_to category_path(@category)
    else
      render new
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    # raise
    if @category.save
      redirect_to @category, notice: "Category has been successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path, notice: "#{@category.name} has been successfully deleted!"
    else
      redirect_to categories_path, alert: "Category could not be deleted."
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a new bookmark page</h1>
<%= simple_form_for [@category, @bookmark] do |f| %>
<%= f.association :recipe, collection: Recipe.all, label_method: :name, value_method: :id, label:"Select Recipe" %>
<%= f.input :comment, label:"comment" %>
<%= f.submit "Create Bookmark" %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories Index Page</h1>
<div>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %>
    <%= button_to "Delete", category_path(category), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>
<%= link_to "Add Category", new_category_path %>
</div>

app/views/categories/new.html.erb
<h1>Add a New Category Page</h1>
<div>
  <%= simple_form_for @category do |f| %>
  <%= f.input :name, label: "Category Name" %>
  <%= f.submit "Create Category" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1>Category Show Page</h1>
<div>
<ul>
    <li><%= link_to @category.name, @category %></li>
</ul>
<ul>

<% @category.bookmarks.each do |bookmark| %>
<li> <%= link_to bookmark.recipe.name, bookmark.recipe %> -
  Comment: <%= bookmark.comment %>
  <%= button_to "Delete Bookmark", category_bookmark_path(@category, bookmark), method: :delete, data: {confirm: "Are you sure?"} %>
  </li>
<% end %>
</ul>
<%# <%= link_to "Delete", category_path(@category), method: :delete, data: { confirm: "Are you sure?" } %>
<%= button_to "Delete", category_path(@category), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<%= link_to "Back to All Categories", categories_path %>
<%= link_to "Show All Recipes", recipes_path %>
<%= link_to "Add a recipe", new_category_bookmark_path(@category) %>
<%# <div class="container">
  <h1 class="text-center">Hello, Bootstrap is Working!</h1>
</div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook Redo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes Index Page</h1>
<div>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
    <li><%= recipe.description %></li>
    <li><%= recipe.rating %></li>
    <li><%= image_tag(recipe.image_url) %></li>
    <li><%= button_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>
</div>

app/views/recipes/show.html.erb
<h1>Recipe Show Page</h1>
<div>
<ul>
  <li><%= link_to @recipe.name, @recipe %></li>
  <li><%= @recipe.description %></li>
  <li><%= @recipe.rating %></li>
  <li><%= image_tag(@recipe.image_url) %></li>
</ul>
<%# <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" } %>
<%= button_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<%= link_to "Back to All Recipes", recipes_path %>
<%# <%= link_to "Add to Category", categories_path(recipe_id: @recipe.id), class: "btn btn-primary" %>